### ISSUE TITLE
Permanent "You need at least one tag" error while submit

### ISSUE THREAD

**Issue by Lukas-ger** [dbleu/issues#6]
![image](https://github.com/dbleu/todo/assets/68353308/69232af4-d906-4a4c-b42a-9528dde922cf)
![image](https://github.com/dbleu/todo/assets/68353308/b23129b4-d37c-4305-abf4-560f81a42896)

**Comment by tunikakeks** [comment]
Make sure to press enter after entering one tag. Mobile solution soonTM
